# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 768)
        MainWindow.setMinimumSize(QtCore.QSize(960, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Camera = QtWidgets.QLabel(self.centralwidget)
        self.label_Camera.setGeometry(QtCore.QRect(30, 20, 640, 480))
        self.label_Camera.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Camera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Camera.setText("")
        self.label_Camera.setObjectName("label_Camera")
        self.textBrowser_Console = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Console.setGeometry(QtCore.QRect(30, 520, 641, 201))
        self.textBrowser_Console.setOpenLinks(False)
        self.textBrowser_Console.setObjectName("textBrowser_Console")
        self.label_Target = QtWidgets.QLabel(self.centralwidget)
        self.label_Target.setGeometry(QtCore.QRect(700, 20, 224, 224))
        self.label_Target.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Target.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Target.setText("")
        self.label_Target.setObjectName("label_Target")
        self.label_Generated = QtWidgets.QLabel(self.centralwidget)
        self.label_Generated.setGeometry(QtCore.QRect(700, 270, 224, 224))
        self.label_Generated.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Generated.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Generated.setText("")
        self.label_Generated.setObjectName("label_Generated")
        self.groupBox_TargetPic = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_TargetPic.setGeometry(QtCore.QRect(700, 520, 224, 61))
        self.groupBox_TargetPic.setObjectName("groupBox_TargetPic")
        self.pushButton_OpenCamera = QtWidgets.QPushButton(self.groupBox_TargetPic)
        self.pushButton_OpenCamera.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.pushButton_OpenCamera.setObjectName("pushButton_OpenCamera")
        self.pushButton_CameraCapture = QtWidgets.QPushButton(self.groupBox_TargetPic)
        self.pushButton_CameraCapture.setEnabled(False)
        self.pushButton_CameraCapture.setGeometry(QtCore.QRect(120, 20, 91, 23))
        self.pushButton_CameraCapture.setObjectName("pushButton_CameraCapture")
        self.groupBox_TrainCommands = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_TrainCommands.setGeometry(QtCore.QRect(700, 600, 111, 111))
        self.groupBox_TrainCommands.setObjectName("groupBox_TrainCommands")
        self.pushButton_TrainStart = QtWidgets.QPushButton(self.groupBox_TrainCommands)
        self.pushButton_TrainStart.setGeometry(QtCore.QRect(10, 50, 91, 23))
        self.pushButton_TrainStart.setObjectName("pushButton_TrainStart")
        self.pushButton_TrainStop = QtWidgets.QPushButton(self.groupBox_TrainCommands)
        self.pushButton_TrainStop.setEnabled(False)
        self.pushButton_TrainStop.setGeometry(QtCore.QRect(10, 80, 91, 23))
        self.pushButton_TrainStop.setObjectName("pushButton_TrainStop")
        self.spinBox_ExpectedFPS = QtWidgets.QSpinBox(self.groupBox_TrainCommands)
        self.spinBox_ExpectedFPS.setGeometry(QtCore.QRect(50, 20, 51, 21))
        self.spinBox_ExpectedFPS.setAccelerated(True)
        self.spinBox_ExpectedFPS.setMinimum(1)
        self.spinBox_ExpectedFPS.setMaximum(144)
        self.spinBox_ExpectedFPS.setProperty("value", 8)
        self.spinBox_ExpectedFPS.setObjectName("spinBox_ExpectedFPS")
        self.label_ExpectedFPS = QtWidgets.QLabel(self.groupBox_TrainCommands)
        self.label_ExpectedFPS.setGeometry(QtCore.QRect(20, 20, 31, 21))
        self.label_ExpectedFPS.setObjectName("label_ExpectedFPS")
        self.groupBox_Misc = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Misc.setGeometry(QtCore.QRect(820, 600, 104, 111))
        self.groupBox_Misc.setObjectName("groupBox_Misc")
        self.pushButton_SaveResult = QtWidgets.QPushButton(self.groupBox_Misc)
        self.pushButton_SaveResult.setEnabled(False)
        self.pushButton_SaveResult.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.pushButton_SaveResult.setObjectName("pushButton_SaveResult")
        self.pushButton_Reset = QtWidgets.QPushButton(self.groupBox_Misc)
        self.pushButton_Reset.setGeometry(QtCore.QRect(10, 50, 81, 23))
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 23))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuOptions.addAction(self.actionQuit)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Camera.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">The Camera Frame</span></p></body></html>"))
        self.textBrowser_Console.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Console</span></p></body></html>"))
        self.label_Target.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Target Pic</span></p></body></html>"))
        self.label_Generated.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Result Pic</span></p></body></html>"))
        self.groupBox_TargetPic.setTitle(_translate("MainWindow", "TargetPic"))
        self.pushButton_OpenCamera.setText(_translate("MainWindow", "OpenCamera"))
        self.pushButton_CameraCapture.setText(_translate("MainWindow", "Capture"))
        self.groupBox_TrainCommands.setTitle(_translate("MainWindow", "TrainCommands"))
        self.pushButton_TrainStart.setText(_translate("MainWindow", "Start"))
        self.pushButton_TrainStop.setText(_translate("MainWindow", "Stop"))
        self.spinBox_ExpectedFPS.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Expected FPS</span></p></body></html>"))
        self.label_ExpectedFPS.setText(_translate("MainWindow", "FPS"))
        self.groupBox_Misc.setTitle(_translate("MainWindow", "Misc"))
        self.pushButton_SaveResult.setText(_translate("MainWindow", "SaveResult"))
        self.pushButton_Reset.setText(_translate("MainWindow", "Reset"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
