# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit_Console = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Console.setGeometry(QtCore.QRect(10, 580, 641, 141))
        self.plainTextEdit_Console.setReadOnly(True)
        self.plainTextEdit_Console.setObjectName("plainTextEdit_Console")
        self.pushButton_CameraOpen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CameraOpen.setGeometry(QtCore.QRect(10, 40, 101, 23))
        self.pushButton_CameraOpen.setObjectName("pushButton_CameraOpen")
        self.pushButton_CameraStop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CameraStop.setGeometry(QtCore.QRect(130, 40, 101, 23))
        self.pushButton_CameraStop.setObjectName("pushButton_CameraStop")
        self.label_Camera = QtWidgets.QLabel(self.centralwidget)
        self.label_Camera.setGeometry(QtCore.QRect(10, 80, 640, 480))
        self.label_Camera.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Camera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Camera.setText("")
        self.label_Camera.setObjectName("label_Camera")
        self.pushButton_CameraCapture = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CameraCapture.setGeometry(QtCore.QRect(550, 40, 101, 23))
        self.pushButton_CameraCapture.setObjectName("pushButton_CameraCapture")
        self.label_Capture = QtWidgets.QLabel(self.centralwidget)
        self.label_Capture.setGeometry(QtCore.QRect(690, 80, 640, 480))
        self.label_Capture.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Capture.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_Capture.setText("")
        self.label_Capture.setObjectName("label_Capture")
        self.groupBox_NameOfFace = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_NameOfFace.setGeometry(QtCore.QRect(690, 580, 311, 141))
        self.groupBox_NameOfFace.setObjectName("groupBox_NameOfFace")
        self.label_Name_0 = QtWidgets.QLabel(self.groupBox_NameOfFace)
        self.label_Name_0.setGeometry(QtCore.QRect(10, 20, 16, 21))
        self.label_Name_0.setObjectName("label_Name_0")
        self.lineEdit_Name_0 = QtWidgets.QLineEdit(self.groupBox_NameOfFace)
        self.lineEdit_Name_0.setEnabled(False)
        self.lineEdit_Name_0.setGeometry(QtCore.QRect(30, 20, 113, 20))
        self.lineEdit_Name_0.setObjectName("lineEdit_Name_0")
        self.label_Name_1 = QtWidgets.QLabel(self.groupBox_NameOfFace)
        self.label_Name_1.setGeometry(QtCore.QRect(10, 50, 16, 21))
        self.label_Name_1.setObjectName("label_Name_1")
        self.lineEdit_Name_1 = QtWidgets.QLineEdit(self.groupBox_NameOfFace)
        self.lineEdit_Name_1.setEnabled(False)
        self.lineEdit_Name_1.setGeometry(QtCore.QRect(30, 50, 113, 20))
        self.lineEdit_Name_1.setObjectName("lineEdit_Name_1")
        self.lineEdit_Name_2 = QtWidgets.QLineEdit(self.groupBox_NameOfFace)
        self.lineEdit_Name_2.setEnabled(False)
        self.lineEdit_Name_2.setGeometry(QtCore.QRect(30, 80, 113, 20))
        self.lineEdit_Name_2.setObjectName("lineEdit_Name_2")
        self.label_Name_2 = QtWidgets.QLabel(self.groupBox_NameOfFace)
        self.label_Name_2.setGeometry(QtCore.QRect(10, 80, 16, 21))
        self.label_Name_2.setObjectName("label_Name_2")
        self.lineEdit_Name_3 = QtWidgets.QLineEdit(self.groupBox_NameOfFace)
        self.lineEdit_Name_3.setEnabled(False)
        self.lineEdit_Name_3.setGeometry(QtCore.QRect(30, 110, 113, 20))
        self.lineEdit_Name_3.setObjectName("lineEdit_Name_3")
        self.label_Name_3 = QtWidgets.QLabel(self.groupBox_NameOfFace)
        self.label_Name_3.setGeometry(QtCore.QRect(10, 110, 16, 21))
        self.label_Name_3.setObjectName("label_Name_3")
        self.lineEdit_Name_7 = QtWidgets.QLineEdit(self.groupBox_NameOfFace)
        self.lineEdit_Name_7.setEnabled(False)
        self.lineEdit_Name_7.setGeometry(QtCore.QRect(180, 110, 113, 20))
        self.lineEdit_Name_7.setObjectName("lineEdit_Name_7")
        self.lineEdit_Name_5 = QtWidgets.QLineEdit(self.groupBox_NameOfFace)
        self.lineEdit_Name_5.setEnabled(False)
        self.lineEdit_Name_5.setGeometry(QtCore.QRect(180, 50, 113, 20))
        self.lineEdit_Name_5.setObjectName("lineEdit_Name_5")
        self.label_Name_6 = QtWidgets.QLabel(self.groupBox_NameOfFace)
        self.label_Name_6.setGeometry(QtCore.QRect(160, 80, 16, 21))
        self.label_Name_6.setObjectName("label_Name_6")
        self.label_Name_4 = QtWidgets.QLabel(self.groupBox_NameOfFace)
        self.label_Name_4.setGeometry(QtCore.QRect(160, 20, 16, 21))
        self.label_Name_4.setObjectName("label_Name_4")
        self.label_Name_7 = QtWidgets.QLabel(self.groupBox_NameOfFace)
        self.label_Name_7.setGeometry(QtCore.QRect(160, 110, 16, 21))
        self.label_Name_7.setObjectName("label_Name_7")
        self.label_Name_5 = QtWidgets.QLabel(self.groupBox_NameOfFace)
        self.label_Name_5.setGeometry(QtCore.QRect(160, 50, 16, 21))
        self.label_Name_5.setObjectName("label_Name_5")
        self.lineEdit_Name_6 = QtWidgets.QLineEdit(self.groupBox_NameOfFace)
        self.lineEdit_Name_6.setEnabled(False)
        self.lineEdit_Name_6.setGeometry(QtCore.QRect(180, 80, 113, 20))
        self.lineEdit_Name_6.setObjectName("lineEdit_Name_6")
        self.lineEdit_Name_4 = QtWidgets.QLineEdit(self.groupBox_NameOfFace)
        self.lineEdit_Name_4.setEnabled(False)
        self.lineEdit_Name_4.setGeometry(QtCore.QRect(180, 20, 113, 20))
        self.lineEdit_Name_4.setObjectName("lineEdit_Name_4")
        self.pushButton_NameSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_NameSubmit.setGeometry(QtCore.QRect(1020, 690, 101, 23))
        self.pushButton_NameSubmit.setObjectName("pushButton_NameSubmit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 23))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuOption.addAction(self.actionQuit)
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_CameraOpen, self.pushButton_CameraStop)
        MainWindow.setTabOrder(self.pushButton_CameraStop, self.pushButton_CameraCapture)
        MainWindow.setTabOrder(self.pushButton_CameraCapture, self.plainTextEdit_Console)
        MainWindow.setTabOrder(self.plainTextEdit_Console, self.lineEdit_Name_0)
        MainWindow.setTabOrder(self.lineEdit_Name_0, self.lineEdit_Name_1)
        MainWindow.setTabOrder(self.lineEdit_Name_1, self.lineEdit_Name_2)
        MainWindow.setTabOrder(self.lineEdit_Name_2, self.lineEdit_Name_3)
        MainWindow.setTabOrder(self.lineEdit_Name_3, self.lineEdit_Name_4)
        MainWindow.setTabOrder(self.lineEdit_Name_4, self.lineEdit_Name_5)
        MainWindow.setTabOrder(self.lineEdit_Name_5, self.lineEdit_Name_6)
        MainWindow.setTabOrder(self.lineEdit_Name_6, self.lineEdit_Name_7)
        MainWindow.setTabOrder(self.lineEdit_Name_7, self.pushButton_NameSubmit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_CameraOpen.setText(_translate("MainWindow", "Open Camera"))
        self.pushButton_CameraStop.setText(_translate("MainWindow", "Stop Camera"))
        self.pushButton_CameraCapture.setText(_translate("MainWindow", "Capture"))
        self.groupBox_NameOfFace.setTitle(_translate("MainWindow", "Names to save by Order"))
        self.label_Name_0.setText(_translate("MainWindow", "0"))
        self.label_Name_1.setText(_translate("MainWindow", "1"))
        self.label_Name_2.setText(_translate("MainWindow", "2"))
        self.label_Name_3.setText(_translate("MainWindow", "3"))
        self.label_Name_6.setText(_translate("MainWindow", "6"))
        self.label_Name_4.setText(_translate("MainWindow", "4"))
        self.label_Name_7.setText(_translate("MainWindow", "7"))
        self.label_Name_5.setText(_translate("MainWindow", "5"))
        self.pushButton_NameSubmit.setText(_translate("MainWindow", "Submit"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
