# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_PredPosibiity = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_PredPosibiity.setGeometry(QtCore.QRect(0, 330, 801, 61))
        self.tableWidget_PredPosibiity.setAutoFillBackground(False)
        self.tableWidget_PredPosibiity.setMidLineWidth(1)
        self.tableWidget_PredPosibiity.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_PredPosibiity.setAlternatingRowColors(False)
        self.tableWidget_PredPosibiity.setShowGrid(True)
        self.tableWidget_PredPosibiity.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_PredPosibiity.setRowCount(1)
        self.tableWidget_PredPosibiity.setObjectName("tableWidget_PredPosibiity")
        self.tableWidget_PredPosibiity.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PredPosibiity.setHorizontalHeaderItem(9, item)
        self.tableWidget_PredPosibiity.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_PredPosibiity.horizontalHeader().setDefaultSectionSize(78)
        self.groupBox_DrawForPrediction = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_DrawForPrediction.setGeometry(QtCore.QRect(580, 10, 201, 61))
        self.groupBox_DrawForPrediction.setObjectName("groupBox_DrawForPrediction")
        self.pushButton_Predict = QtWidgets.QPushButton(self.groupBox_DrawForPrediction)
        self.pushButton_Predict.setGeometry(QtCore.QRect(20, 20, 71, 23))
        self.pushButton_Predict.setObjectName("pushButton_Predict")
        self.pushButton_ClearCanvas = QtWidgets.QPushButton(self.groupBox_DrawForPrediction)
        self.pushButton_ClearCanvas.setGeometry(QtCore.QRect(110, 20, 71, 23))
        self.pushButton_ClearCanvas.setObjectName("pushButton_ClearCanvas")
        self.groupBox_DataAugmentation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_DataAugmentation.setGeometry(QtCore.QRect(270, 10, 291, 81))
        self.groupBox_DataAugmentation.setObjectName("groupBox_DataAugmentation")
        self.checkBox_RandomBrightness = QtWidgets.QCheckBox(self.groupBox_DataAugmentation)
        self.checkBox_RandomBrightness.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.checkBox_RandomBrightness.setChecked(False)
        self.checkBox_RandomBrightness.setObjectName("checkBox_RandomBrightness")
        self.checkBox_RandomCrop = QtWidgets.QCheckBox(self.groupBox_DataAugmentation)
        self.checkBox_RandomCrop.setGeometry(QtCore.QRect(170, 20, 111, 21))
        self.checkBox_RandomCrop.setChecked(True)
        self.checkBox_RandomCrop.setObjectName("checkBox_RandomCrop")
        self.checkBox_RandomShift = QtWidgets.QCheckBox(self.groupBox_DataAugmentation)
        self.checkBox_RandomShift.setGeometry(QtCore.QRect(170, 50, 111, 21))
        self.checkBox_RandomShift.setChecked(True)
        self.checkBox_RandomShift.setObjectName("checkBox_RandomShift")
        self.checkBox_RandomContrast = QtWidgets.QCheckBox(self.groupBox_DataAugmentation)
        self.checkBox_RandomContrast.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.checkBox_RandomContrast.setChecked(False)
        self.checkBox_RandomContrast.setObjectName("checkBox_RandomContrast")
        self.textBrowser_Console = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Console.setGeometry(QtCore.QRect(0, 390, 801, 161))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC Regular")
        font.setPointSize(11)
        self.textBrowser_Console.setFont(font)
        self.textBrowser_Console.setAcceptDrops(False)
        self.textBrowser_Console.setOpenLinks(False)
        self.textBrowser_Console.setObjectName("textBrowser_Console")
        self.groupBox_TrainCommands = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_TrainCommands.setGeometry(QtCore.QRect(270, 200, 291, 81))
        self.groupBox_TrainCommands.setObjectName("groupBox_TrainCommands")
        self.pushButton_TrainStart = QtWidgets.QPushButton(self.groupBox_TrainCommands)
        self.pushButton_TrainStart.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.pushButton_TrainStart.setObjectName("pushButton_TrainStart")
        self.pushButton_TrainReset = QtWidgets.QPushButton(self.groupBox_TrainCommands)
        self.pushButton_TrainReset.setGeometry(QtCore.QRect(180, 30, 91, 31))
        self.pushButton_TrainReset.setObjectName("pushButton_TrainReset")
        self.label_TableTitle = QtWidgets.QLabel(self.centralwidget)
        self.label_TableTitle.setGeometry(QtCore.QRect(260, 300, 291, 21))
        self.label_TableTitle.setObjectName("label_TableTitle")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 280, 801, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_TrainingParameters = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_TrainingParameters.setGeometry(QtCore.QRect(270, 100, 291, 91))
        self.groupBox_TrainingParameters.setObjectName("groupBox_TrainingParameters")
        self.label_LearningRate = QtWidgets.QLabel(self.groupBox_TrainingParameters)
        self.label_LearningRate.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_LearningRate.setObjectName("label_LearningRate")
        self.doubleSpinBox_LearningRate = QtWidgets.QDoubleSpinBox(self.groupBox_TrainingParameters)
        self.doubleSpinBox_LearningRate.setGeometry(QtCore.QRect(90, 20, 61, 22))
        self.doubleSpinBox_LearningRate.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_LearningRate.setAccelerated(True)
        self.doubleSpinBox_LearningRate.setDecimals(4)
        self.doubleSpinBox_LearningRate.setMinimum(0.0001)
        self.doubleSpinBox_LearningRate.setMaximum(3.0)
        self.doubleSpinBox_LearningRate.setSingleStep(0.01)
        self.doubleSpinBox_LearningRate.setProperty("value", 0.01)
        self.doubleSpinBox_LearningRate.setObjectName("doubleSpinBox_LearningRate")
        self.label_Epochs = QtWidgets.QLabel(self.groupBox_TrainingParameters)
        self.label_Epochs.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_Epochs.setObjectName("label_Epochs")
        self.spinBox_Epochs = QtWidgets.QSpinBox(self.groupBox_TrainingParameters)
        self.spinBox_Epochs.setGeometry(QtCore.QRect(90, 50, 61, 22))
        self.spinBox_Epochs.setAccelerated(True)
        self.spinBox_Epochs.setMinimum(1)
        self.spinBox_Epochs.setMaximum(1000)
        self.spinBox_Epochs.setProperty("value", 20)
        self.spinBox_Epochs.setObjectName("spinBox_Epochs")
        self.checkBox_EarlyStopping = QtWidgets.QCheckBox(self.groupBox_TrainingParameters)
        self.checkBox_EarlyStopping.setGeometry(QtCore.QRect(170, 50, 101, 21))
        self.checkBox_EarlyStopping.setChecked(True)
        self.checkBox_EarlyStopping.setObjectName("checkBox_EarlyStopping")
        self.comboBox_Optimizers = QtWidgets.QComboBox(self.groupBox_TrainingParameters)
        self.comboBox_Optimizers.setGeometry(QtCore.QRect(170, 20, 101, 22))
        self.comboBox_Optimizers.setObjectName("comboBox_Optimizers")
        self.comboBox_Optimizers.addItem("")
        self.comboBox_Optimizers.addItem("")
        self.comboBox_Optimizers.addItem("")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(560, 0, 20, 291))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.frame_Canvas = QtWidgets.QFrame(self.centralwidget)
        self.frame_Canvas.setGeometry(QtCore.QRect(580, 80, 201, 201))
        self.frame_Canvas.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Canvas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Canvas.setObjectName("frame_Canvas")
        self.frame_Canvas.raise_()
        self.tableWidget_PredPosibiity.raise_()
        self.groupBox_DrawForPrediction.raise_()
        self.groupBox_DataAugmentation.raise_()
        self.textBrowser_Console.raise_()
        self.groupBox_TrainCommands.raise_()
        self.label_TableTitle.raise_()
        self.line.raise_()
        self.groupBox_TrainingParameters.raise_()
        self.line_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuOptions.addAction(self.actionQuit)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget_PredPosibiity.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_PredPosibiity.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_PredPosibiity.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_PredPosibiity.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_PredPosibiity.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_PredPosibiity.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_PredPosibiity.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_PredPosibiity.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_PredPosibiity.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_PredPosibiity.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "9"))
        self.groupBox_DrawForPrediction.setTitle(_translate("MainWindow", "DrawForPrediction"))
        self.pushButton_Predict.setText(_translate("MainWindow", "Predict"))
        self.pushButton_ClearCanvas.setText(_translate("MainWindow", "Clear"))
        self.groupBox_DataAugmentation.setTitle(_translate("MainWindow", "DataAugmentation"))
        self.checkBox_RandomBrightness.setText(_translate("MainWindow", "RandomBrightness"))
        self.checkBox_RandomCrop.setText(_translate("MainWindow", "RandomCrop"))
        self.checkBox_RandomShift.setText(_translate("MainWindow", "RandomShift"))
        self.checkBox_RandomContrast.setText(_translate("MainWindow", "RandomContrast"))
        self.groupBox_TrainCommands.setTitle(_translate("MainWindow", "TrainCommands"))
        self.pushButton_TrainStart.setText(_translate("MainWindow", "Start"))
        self.pushButton_TrainReset.setText(_translate("MainWindow", "Reset"))
        self.label_TableTitle.setText(_translate("MainWindow", "Table of predicted Probabilities for the Canvas"))
        self.groupBox_TrainingParameters.setTitle(_translate("MainWindow", "TrainingParameters"))
        self.label_LearningRate.setText(_translate("MainWindow", "LearningRate"))
        self.label_Epochs.setText(_translate("MainWindow", "Epochs"))
        self.checkBox_EarlyStopping.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Early Stopping after 5 epochs if the model not improved.</span></p></body></html>"))
        self.checkBox_EarlyStopping.setText(_translate("MainWindow", "EarlyStopping"))
        self.comboBox_Optimizers.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Optimizers</span></p></body></html>"))
        self.comboBox_Optimizers.setItemText(0, _translate("MainWindow", "SGD"))
        self.comboBox_Optimizers.setItemText(1, _translate("MainWindow", "Adam"))
        self.comboBox_Optimizers.setItemText(2, _translate("MainWindow", "RmsProp"))
        self.frame_Canvas.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
