# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_ContentPic = QtWidgets.QLabel(self.centralwidget)
        self.label_ContentPic.setGeometry(QtCore.QRect(20, 10, 480, 320))
        self.label_ContentPic.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ContentPic.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_ContentPic.setText("")
        self.label_ContentPic.setObjectName("label_ContentPic")
        self.label_StylePic = QtWidgets.QLabel(self.centralwidget)
        self.label_StylePic.setGeometry(QtCore.QRect(20, 350, 480, 320))
        self.label_StylePic.setFrameShape(QtWidgets.QFrame.Box)
        self.label_StylePic.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_StylePic.setText("")
        self.label_StylePic.setObjectName("label_StylePic")
        self.label_ResultPic = QtWidgets.QLabel(self.centralwidget)
        self.label_ResultPic.setGeometry(QtCore.QRect(520, 10, 480, 320))
        self.label_ResultPic.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ResultPic.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_ResultPic.setText("")
        self.label_ResultPic.setObjectName("label_ResultPic")
        self.plainTextEdit_Console = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Console.setGeometry(QtCore.QRect(520, 350, 480, 320))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Console.setFont(font)
        self.plainTextEdit_Console.setReadOnly(True)
        self.plainTextEdit_Console.setObjectName("plainTextEdit_Console")
        self.groupBox_ContentPic = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ContentPic.setGeometry(QtCore.QRect(20, 680, 291, 61))
        self.groupBox_ContentPic.setObjectName("groupBox_ContentPic")
        self.pushButton_ImportContentPicFile = QtWidgets.QPushButton(self.groupBox_ContentPic)
        self.pushButton_ImportContentPicFile.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.pushButton_ImportContentPicFile.setObjectName("pushButton_ImportContentPicFile")
        self.pushButton_CameraOpen = QtWidgets.QPushButton(self.groupBox_ContentPic)
        self.pushButton_CameraOpen.setGeometry(QtCore.QRect(110, 20, 81, 23))
        self.pushButton_CameraOpen.setObjectName("pushButton_CameraOpen")
        self.pushButton_CameraCapture = QtWidgets.QPushButton(self.groupBox_ContentPic)
        self.pushButton_CameraCapture.setEnabled(False)
        self.pushButton_CameraCapture.setGeometry(QtCore.QRect(200, 20, 81, 23))
        self.pushButton_CameraCapture.setObjectName("pushButton_CameraCapture")
        self.groupBox_StylePic = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_StylePic.setGeometry(QtCore.QRect(330, 680, 111, 61))
        self.groupBox_StylePic.setObjectName("groupBox_StylePic")
        self.pushButton_ImportStylePicFile = QtWidgets.QPushButton(self.groupBox_StylePic)
        self.pushButton_ImportStylePicFile.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.pushButton_ImportStylePicFile.setObjectName("pushButton_ImportStylePicFile")
        self.groupBox_TrainStyleTransferModel = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_TrainStyleTransferModel.setGeometry(QtCore.QRect(460, 680, 321, 61))
        self.groupBox_TrainStyleTransferModel.setObjectName("groupBox_TrainStyleTransferModel")
        self.pushButton_TrainModel = QtWidgets.QPushButton(self.groupBox_TrainStyleTransferModel)
        self.pushButton_TrainModel.setGeometry(QtCore.QRect(160, 20, 71, 23))
        self.pushButton_TrainModel.setObjectName("pushButton_TrainModel")
        self.pushButton_TrainTerminate = QtWidgets.QPushButton(self.groupBox_TrainStyleTransferModel)
        self.pushButton_TrainTerminate.setEnabled(False)
        self.pushButton_TrainTerminate.setGeometry(QtCore.QRect(240, 20, 71, 23))
        self.pushButton_TrainTerminate.setObjectName("pushButton_TrainTerminate")
        self.spinBox_ExpectedFPS = QtWidgets.QSpinBox(self.groupBox_TrainStyleTransferModel)
        self.spinBox_ExpectedFPS.setGeometry(QtCore.QRect(90, 20, 51, 22))
        self.spinBox_ExpectedFPS.setMinimum(1)
        self.spinBox_ExpectedFPS.setMaximum(1000)
        self.spinBox_ExpectedFPS.setProperty("value", 8)
        self.spinBox_ExpectedFPS.setObjectName("spinBox_ExpectedFPS")
        self.label_ExpectedFPS = QtWidgets.QLabel(self.groupBox_TrainStyleTransferModel)
        self.label_ExpectedFPS.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_ExpectedFPS.setObjectName("label_ExpectedFPS")
        self.groupBox_Misc = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Misc.setGeometry(QtCore.QRect(800, 679, 201, 61))
        self.groupBox_Misc.setObjectName("groupBox_Misc")
        self.pushButton_Reset = QtWidgets.QPushButton(self.groupBox_Misc)
        self.pushButton_Reset.setGeometry(QtCore.QRect(140, 20, 51, 23))
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.pushButton_DownloadResultPic = QtWidgets.QPushButton(self.groupBox_Misc)
        self.pushButton_DownloadResultPic.setEnabled(False)
        self.pushButton_DownloadResultPic.setGeometry(QtCore.QRect(10, 20, 121, 23))
        self.pushButton_DownloadResultPic.setObjectName("pushButton_DownloadResultPic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuOptions.addAction(self.actionQuit)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_ContentPic.setToolTip(_translate("MainWindow", "<html><head/><body><p>Shows Content Pic</p></body></html>"))
        self.label_StylePic.setToolTip(_translate("MainWindow", "<html><head/><body><p>Shows Style Pic</p></body></html>"))
        self.label_ResultPic.setToolTip(_translate("MainWindow", "<html><head/><body><p>Shows Result Image</p></body></html>"))
        self.plainTextEdit_Console.setToolTip(_translate("MainWindow", "<html><head/><body><p>Console</p></body></html>"))
        self.groupBox_ContentPic.setTitle(_translate("MainWindow", "ContentPic"))
        self.pushButton_ImportContentPicFile.setText(_translate("MainWindow", "ImportPicFile"))
        self.pushButton_CameraOpen.setText(_translate("MainWindow", "OpenCamera"))
        self.pushButton_CameraCapture.setText(_translate("MainWindow", "Capture"))
        self.groupBox_StylePic.setTitle(_translate("MainWindow", "StylePic"))
        self.pushButton_ImportStylePicFile.setText(_translate("MainWindow", "ImportPicFile"))
        self.groupBox_TrainStyleTransferModel.setTitle(_translate("MainWindow", "TrainStyleTransferModel"))
        self.pushButton_TrainModel.setText(_translate("MainWindow", "Train"))
        self.pushButton_TrainTerminate.setText(_translate("MainWindow", "Terminate"))
        self.label_ExpectedFPS.setText(_translate("MainWindow", "ExpectedFPS"))
        self.groupBox_Misc.setTitle(_translate("MainWindow", "Misc"))
        self.pushButton_Reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_DownloadResultPic.setText(_translate("MainWindow", "DownloadResultPic"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
